name: Build
on:
  push:
    branches:
      - master
      - "*.*.*"
  pull_request:
    branches:
      - "*.*.*"
jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Lint
        run: lein lint src test --cache false
  test:
    needs: build
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    services:
      aerospike-test:
        image: aerospike
        ports:
          - 3000:3000
          - 3001:3001
          - 3002:3002
          - 3003:3003
    env:
      AEROSPIKE_HOST: localhost
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: "Unit tests"
        run: lein eftest
  deploy:
    needs: test
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: "Deploy SNAPSHOT"
        env:
          SNAPSHOT_REGEX: ^[0-9]{1,2}[.][0-9]{1,2}[.][0-9]{1,3}-SNAPSHOT$
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        if: github.event_name != 'pull_request' && env.CLOJARS_PASSWORD != ''
        run: |
          export BRANCH=$(echo "$GITHUB_REF" | cut -d "/" -f3)
          echo "Branch is:" $BRANCH
          lein install
          export VERSION=$(less pom.xml | grep "<version>" | head -1 | cut -d ">" -f2 | cut -d "<" -f1)
          echo "Version is:" $VERSION
          if [[ !("$VERSION" =~ $SNAPSHOT_REGEX) ]] || [[ "$BRANCH" = master ]]; then echo "Snapashot version" $VERSION "is not valid"; exit 1; fi
          lein deploy
          echo "Snapshot version" $VERSION "successfully deployed to Clojars"
