name: aerospike-clj CI
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Lint
        run: lein lint src test --cache false
  test:
    needs: build
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    services:
      aerospike-test:
        image: aerospike
        ports:
          - 3000:3000
          - 3001:3001
          - 3002:3002
          - 3003:3003
    env:
      AEROSPIKE_HOST: localhost
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: "Unit tests"
        run: lein eftest
#      - name: "Integration tests"
#        run: lein eftest :integration
